# Make sure to increase resource requests and limits before using this example in production.
# For examples with more realistic resource configuration, see
# ray-cluster.complete.large.yaml and
# ray-cluster.autoscaler.large.yaml.
apiVersion: ray.io/v1alpha1
kind: RayService
metadata:
  name: serve-amazon-light-gpt
spec:
  serviceUnhealthySecondThreshold: 900 # Config for the health check threshold for Ray Serve applications. Default value is 900.
  deploymentUnhealthySecondThreshold: 300 # Config for the health check threshold for Ray dashboard agent. Default value is 300.
  serveService:
    metadata:
      name: serve-amazon-light-gpt
      labels:
        custom-label: serve-amazon-light-gpt-label
      annotations:
        custom-annotation: serve-amazon-light-gpt-annotation
    spec:
      type: NodePort
      ports:
        - port: 8000
          nodePort: 32345
          name: serve-amazon-light-gpt-port
  serveConfigV2: |
    applications:
      - name: serve-amazon-light-gpt
        import_path: ray_main.app
        route_prefix: /frontend
        runtime_env:
          working_dir: "https://raw.githubusercontent.com/aiwantaozi/my-llm-frontend/terraform-test/my-llm-frontend.zip"
          pip:
            - gradio
  # serveConfig:
  #   importPath: ray_main.app
  #   runtimeEnv: |
  #     working_dir: "https://raw.githubusercontent.com/aiwantaozi/my-llm-frontend/terraform-test/my-llm-frontend.zip"
  #     pip:
  #      - gradio
  rayClusterConfig:
    rayVersion: "2.7.0" # should match the Ray version in the image of the containers
    ######################headGroupSpecs#################################
    # Ray head pod template.
    headGroupSpec:
      # The `rayStartParams` are used to configure the `ray start` command.
      # See https://github.com/ray-project/kuberay/blob/master/docs/guidance/rayStartParams.md for the default settings of `rayStartParams` in KubeRay.
      # See https://docs.ray.io/en/latest/cluster/cli.html#ray-start for all available options in `rayStartParams`.
      rayStartParams:
        dashboard-host: "0.0.0.0"
      #pod template
      template:
        spec:
          containers:
            - name: ray-head
              image: rayproject/ray:2.7.0
              env: 
              - name: MODEL_NAME
                value: amazon/LightGPT
              - name: BACKEND_URL
                value: "http://amazon-light-gpt-serve-svc:8000"
              resources:
                limits:
                  cpu: 1
                  memory: 1Gi
                requests:
                  cpu: 1
                  memory: 1Gi
              ports:
                - containerPort: 6379
                  name: gcs-server
                - containerPort: 8265 # Ray dashboard
                  name: dashboard
                - containerPort: 10001
                  name: client
                - containerPort: 8000
                  name: serve
    workerGroupSpecs:
      # the pod replicas in this group typed worker
      - replicas: 1
        minReplicas: 1
        maxReplicas: 5
        # logical group name, for this called small-group, also can be functional
        groupName: small-group
        # The `rayStartParams` are used to configure the `ray start` command.
        # See https://github.com/ray-project/kuberay/blob/master/docs/guidance/rayStartParams.md for the default settings of `rayStartParams` in KubeRay.
        # See https://docs.ray.io/en/latest/cluster/cli.html#ray-start for all available options in `rayStartParams`.
        rayStartParams: {}
        #pod template
        template:
          spec:
            containers:
              - name: ray-worker # must consist of lower case alphanumeric characters or '-', and must start and end with an alphanumeric character (e.g. 'my-name',  or '123-abc'
                image: rayproject/ray:2.7.0
                lifecycle:
                  preStop:
                    exec:
                      command: ["/bin/sh", "-c", "ray stop"]
                env: 
                - name: MODEL_NAME
                  value: test
                - name: BACKEND_URL
                  value: "http://192.168.0.9:1323"
                resources:
                  limits:
                    cpu: "500m"
                    memory: "1Gi"
                  requests:
                    cpu: "500m"
                    memory: "1Gi"
